# Generated by Django 5.2.4 on 2025-07-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Proyecto',
                'verbose_name_plural': 'Categorías de Proyectos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion_corta', models.TextField(blank=True, null=True)),
                ('descripcion_larga', models.TextField(blank=True, null=True)),
                ('tipo_proyecto', models.CharField(choices=[('explotacion', 'Explotación'), ('exploracion', 'Exploración'), ('restauracion', 'Restauración'), ('innovacion', 'Innovación'), ('sostenibilidad', 'Sostenibilidad')], max_length=20)),
                ('estado_proyecto', models.CharField(choices=[('planificacion', 'Planificación'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('suspendido', 'Suspendido')], default='en_curso', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('coordenadas_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('coordenadas_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('imagen_principal', models.URLField(blank=True, null=True)),
                ('galeria_imagenes', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('tecnologias_utilizadas', models.JSONField(blank=True, default=list)),
                ('resultados', models.JSONField(blank=True, default=list)),
                ('impacto_ambiental', models.TextField(blank=True, null=True)),
                ('beneficios_comunidad', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('destacado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
    ]
