# Generated by Django 5.2.4 on 2025-07-29 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría del proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.categoriaproyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagen_principal_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen principal (alternativa)', null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='Imagen principal subida al servidor (recomendado: JPG, PNG)', null=True, upload_to='proyectos/'),
        ),
    ]
