# Generated by Django 5.2.4 on 2025-07-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_categoria_proyecto_imagen_principal_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='tipo_proyecto',
        ),
    ]
