# Generated by Django 5.2.4 on 2025-07-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('asunto', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje', models.TextField()),
                ('tipo_consulta', models.CharField(choices=[('general', 'General'), ('cotizacion', 'Cotización'), ('trabajo', 'Trabajo'), ('prensa', 'Prensa'), ('inversion', 'Inversión')], default='general', max_length=20)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_revision', 'En Revisión'), ('respondido', 'Respondido'), ('archivado', 'Archivado')], default='nuevo', max_length=20)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('fecha_contacto', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-fecha_contacto'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('intereses', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('baja', 'Baja')], default='activo', max_length=20)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Suscriptor Newsletter',
                'verbose_name_plural': 'Suscriptores Newsletter',
                'ordering': ['-fecha_suscripcion'],
            },
        ),
    ]
