# Generated by Django 5.2.4 on 2025-07-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificacionPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('certificacion', 'Certificación'), ('premio', 'Premio'), ('reconocimiento', 'Reconocimiento')], max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('organismo_otorgante', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_otorgamiento', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('logo_certificacion', models.URLField(blank=True, null=True)),
                ('documento_certificacion', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vencido', 'Vencido'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificación/Premio',
                'verbose_name_plural': 'Certificaciones y Premios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='Minera Fidami S.A.', max_length=255)),
                ('slogan', models.TextField(blank=True, default='Líderes en Minería Sostenible y Eficiente', null=True)),
                ('descripcion_corta', models.TextField(blank=True, null=True)),
                ('descripcion_larga', models.TextField(blank=True, null=True)),
                ('mision', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('valores', models.JSONField(blank=True, default=list)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('favicon_url', models.URLField(blank=True, null=True)),
                ('email_contacto', models.EmailField(blank=True, default='recepcion@minerafidami.com.pe', max_length=254, null=True)),
                ('telefono_principal', models.CharField(blank=True, default='+51 914599576', max_length=50, null=True)),
                ('direccion_oficina', models.TextField(blank=True, default='Sancos Lucanas, Ayacucho', null=True)),
                ('coordenadas_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('coordenadas_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('horario_atencion', models.CharField(blank=True, max_length=255, null=True)),
                ('redes_sociales', models.JSONField(blank=True, default=dict)),
                ('meta_title_default', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description_default', models.TextField(blank=True, null=True)),
                ('meta_keywords_default', models.TextField(blank=True, null=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración General',
                'verbose_name_plural': 'Configuración General',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('experiencia_anos', models.IntegerField(blank=True, null=True)),
                ('especialidades', models.JSONField(blank=True, default=list)),
                ('educacion', models.JSONField(blank=True, default=list)),
                ('certificaciones', models.JSONField(blank=True, default=list)),
                ('foto', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('directivo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Miembro del Equipo',
                'verbose_name_plural': 'Miembros del Equipo',
                'ordering': ['orden', 'apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('imagen_principal', models.URLField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('borrador', 'Borrador')], default='activo', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('testimonio', models.TextField()),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('proyecto_relacionado', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
