# Generated by Django 5.2.4 on 2025-07-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('tiktok', 'TikTok'), ('github', 'GitHub'), ('website', 'Sitio Web')], max_length=50)),
                ('url', models.URLField()),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono (opcional)', max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text='Color hexadecimal (ej: #1877F2)', max_length=7, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('nombre',)},
            },
        ),
    ]
