# Generated by Django 5.2.4 on 2025-07-28 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_redsocial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuraciongeneral',
            name='redes_sociales',
        ),
    ]
