# Generated by Django 5.2.4 on 2025-07-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_configuraciongeneral_redes_sociales'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(default='HACIENDO LO COMPLEJO SIMPLE', max_length=255)),
                ('subtitulo', models.TextField(default='Líderes en minería sostenible y eficiente. Comprometidos con la seguridad, la innovación y el respeto al medio ambiente.')),
                ('imagen_fondo', models.URLField(blank=True, help_text='URL de la imagen de fondo del hero section', null=True)),
                ('texto_boton_principal', models.CharField(default='Contáctanos', max_length=100)),
                ('url_boton_principal', models.CharField(default='contacto', max_length=255)),
                ('texto_boton_secundario', models.CharField(default='Explora nuestros proyectos', max_length=100)),
                ('url_boton_secundario', models.CharField(default='proyectos', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error')], default='info', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['orden', '-created_at'],
            },
        ),
    ]
