# Generated by Django 5.2.4 on 2025-07-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_herosection_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon de la empresa (recomendado: ICO, PNG)', null=True, upload_to='configuracion/'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la empresa (recomendado: PNG, SVG)', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='URL externa del favicon (alternativa)', null=True),
        ),
        migrations.AlterField(
            model_name='configuraciongeneral',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL externa del logo (alternativa)', null=True),
        ),
    ]
