# Generated by Django 5.2.4 on 2025-07-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configuraciongeneral_favicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificacionpremio',
            name='documento_certificacion',
        ),
        migrations.RemoveField(
            model_name='certificacionpremio',
            name='logo_certificacion',
        ),
        migrations.AddField(
            model_name='certificacionpremio',
            name='url_documento',
            field=models.URLField(blank=True, help_text='URL del documento de la certificación', null=True),
        ),
        migrations.AddField(
            model_name='certificacionpremio',
            name='url_logo',
            field=models.URLField(blank=True, help_text='URL del logo de la certificación', null=True),
        ),
    ]
