# Generated by Django 5.2.4 on 2025-07-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_certificacionpremio_documento_certificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='imagen_fondo_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen de fondo (alternativa)', null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='imagen_fondo',
            field=models.ImageField(blank=True, help_text='Imagen de fondo subida al servidor (recomendado: JPG, PNG)', null=True, upload_to='hero_sections/'),
        ),
    ]
