# Generated by Django 5.2.4 on 2025-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_herosection_imagen_fondo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='foto_url',
            field=models.URLField(blank=True, help_text='URL externa de la foto (alternativa)', null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto subida al servidor (recomendado: JPG, PNG)', null=True, upload_to='equipo/'),
        ),
    ]
