# Generated by Django 5.2.4 on 2025-07-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_equipo_foto_url_alter_equipo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen (alternativa)', null=True),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen subida al servidor (recomendado: JPG, PNG)', null=True, upload_to='testimonios/'),
        ),
    ]
