# Generated by Django 5.2.4 on 2025-08-06 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_testimonio_imagen_url_alter_testimonio_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
