# Generated by Django 5.2.4 on 2025-08-06 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_mensaje_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagina',
        ),
    ]
