# Generated by Django 5.2.4 on 2025-08-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_pagina_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre que aparecerá en el navbar', max_length=100)),
                ('url', models.URLField(help_text='URL completa del enlace externo')),
                ('tipo', models.CharField(choices=[('accionista', 'Accionista'), ('inversionista', 'Inversionista'), ('proveedor', 'Proveedor'), ('empleado', 'Empleado'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el navbar')),
                ('activo', models.BooleanField(default=True, help_text='Si el enlace está activo')),
                ('abrir_nueva_ventana', models.BooleanField(default=True, help_text='Si el enlace debe abrirse en nueva ventana')),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del icono (ej: fas fa-external-link-alt)', max_length=50)),
            ],
            options={
                'verbose_name': 'Enlace Externo',
                'verbose_name_plural': 'Enlaces Externos',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
