# Generated by Django 5.2.4 on 2025-08-06 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaComunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Color en formato hexadecimal', max_length=7)),
                ('icono', models.CharField(default='fas fa-bullhorn', help_text='Clase de icono FontAwesome', max_length=50)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Comunicado',
                'verbose_name_plural': 'Categorías de Comunicados',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('resumen', models.TextField(blank=True, help_text='Resumen corto del comunicado', null=True)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('urgente', 'Urgente'), ('importante', 'Importante'), ('informativo', 'Informativo'), ('evento', 'Evento'), ('mantenimiento', 'Mantenimiento'), ('seguridad', 'Seguridad'), ('operacional', 'Operacional')], default='informativo', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('critica', 'Crítica')], default='normal', max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', max_length=20)),
                ('mostrar_en_home', models.BooleanField(default=False, help_text='Mostrar como notificación en la página principal')),
                ('mostrar_en_popup', models.BooleanField(default=False, help_text='Mostrar como popup emergente')),
                ('destacado', models.BooleanField(default=False, help_text='Marcar como comunicado destacado')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha hasta cuando mostrar el comunicado', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('etiquetas', models.JSONField(blank=True, default=list, help_text='Etiquetas para categorización')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo PDF o documento adjunto', null=True, upload_to='comunicados/adjuntos/')),
                ('imagen_destacada', models.ImageField(blank=True, help_text='Imagen destacada del comunicado', null=True, upload_to='comunicados/imagenes/')),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('descargas', models.PositiveIntegerField(default=0)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados', to='comunicados.categoriacomunicado')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-fecha_publicacion', '-prioridad', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ComunicadoVista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha_vista', models.DateTimeField(auto_now_add=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_vistas', to='comunicados.comunicado')),
            ],
            options={
                'verbose_name': 'Vista de Comunicado',
                'verbose_name_plural': 'Vistas de Comunicados',
                'ordering': ['-fecha_vista'],
            },
        ),
    ]
