# Generated by Django 5.2.4 on 2025-07-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría del Blog',
                'verbose_name_plural': 'Categorías del Blog',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(blank=True, max_length=500, null=True)),
                ('contenido', models.TextField()),
                ('resumen', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('noticia', 'Noticia'), ('articulo', 'Artículo'), ('comunicado', 'Comunicado'), ('blog', 'Blog')], default='noticia', max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('etiquetas', models.JSONField(blank=True, default=list)),
                ('imagen_principal', models.URLField(blank=True, null=True)),
                ('galeria_imagenes', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('vistas', models.IntegerField(default=0)),
                ('destacado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.equipo')),
            ],
            options={
                'verbose_name': 'Noticia/Blog',
                'verbose_name_plural': 'Noticias y Blog',
                'ordering': ['-fecha_publicacion', 'titulo'],
            },
        ),
    ]
