# Generated by Django 5.2.4 on 2025-07-28 23:54

from django.db import migrations


def crear_categorias_existentes(apps, schema_editor):
    """Crear categorías basadas en datos existentes"""
    NoticiaBlog = apps.get_model('blog', 'NoticiaBlog')
    CategoriaBlog = apps.get_model('blog', 'CategoriaBlog')
    
    # Obtener todas las categorías únicas de las noticias existentes
    categorias_existentes = NoticiaBlog.objects.values_list('categoria', flat=True).distinct()
    
    # Crear categorías para cada valor único
    for categoria_nombre in categorias_existentes:
        if categoria_nombre:  # Solo si no es None o vacío
            categoria, created = CategoriaBlog.objects.get_or_create(
                nombre=categoria_nombre,
                defaults={
                    'descripcion': f'Categoría para {categoria_nombre}',
                    'estado': 'activo',
                    'orden': 0
                }
            )
            if created:
                print(f"✅ Categoría creada: {categoria.nombre}")
            else:
                print(f"ℹ️ Categoría ya existe: {categoria.nombre}")


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_categorias_existentes, reverse_code=migrations.RunPython.noop),
    ]
