# Generated by Django 5.2.4 on 2025-07-28 23:54

from django.db import migrations


def limpiar_categorias_existentes(apps, schema_editor):
    """Limpiar las categorías existentes para evitar conflictos"""
    NoticiaBlog = apps.get_model('blog', 'NoticiaBlog')
    
    # Establecer todas las categorías como None para evitar conflictos
    NoticiaBlog.objects.update(categoria=None)
    print("✅ Categorías limpiadas para migración segura")


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250728_1854'),
    ]

    operations = [
        migrations.RunPython(limpiar_categorias_existentes, reverse_code=migrations.RunPython.noop),
    ]
