# Generated by Django 5.2.4 on 2025-07-28 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250728_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiablog',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='blog.categoriablog'),
        ),
    ]
