# Generated by Django 5.2.4 on 2025-07-29 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_noticiablog_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriablog',
            name='imagen',
        ),
    ]
