# Generated by Django 5.2.4 on 2025-07-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_categoriablog_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiablog',
            name='imagen_principal_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen principal (alternativa)', null=True),
        ),
        migrations.AlterField(
            model_name='noticiablog',
            name='galeria_imagenes',
            field=models.JSONField(blank=True, default=list, help_text='URLs de imágenes de la galería'),
        ),
        migrations.AlterField(
            model_name='noticiablog',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='Imagen principal del artículo (recomendado: JPG, PNG)', null=True, upload_to='blog/noticias/'),
        ),
    ]
