# Generated by Django 5.2.4 on 2025-07-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('requisitos', models.JSONField(blank=True, default=list)),
                ('responsabilidades', models.JSONField(blank=True, default=list)),
                ('beneficios', models.JSONField(blank=True, default=list)),
                ('tipo_contrato', models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('tiempo_parcial', 'Tiempo Parcial'), ('contrato', 'Contrato'), ('practicas', 'Prácticas')], max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('experiencia_minima', models.IntegerField(blank=True, null=True)),
                ('experiencia_maxima', models.IntegerField(blank=True, null=True)),
                ('salario_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salario_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('suspendida', 'Suspendida')], default='abierta', max_length=20)),
                ('destacada', models.BooleanField(default=False)),
                ('vistas', models.IntegerField(default=0)),
                ('postulaciones', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'ordering': ['-created_at', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('experiencia_anos', models.IntegerField(blank=True, null=True)),
                ('educacion', models.TextField(blank=True, null=True)),
                ('cv_url', models.URLField(blank=True, null=True)),
                ('carta_motivacion', models.TextField(blank=True, null=True)),
                ('referencias', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('revisando', 'Revisando'), ('entrevista', 'Entrevista'), ('rechazada', 'Rechazada'), ('contratada', 'Contratada')], default='recibida', max_length=20)),
                ('notas_internas', models.TextField(blank=True, null=True)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.vacante')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-fecha_postulacion'],
            },
        ),
    ]
