# Generated by Django 5.2.4 on 2025-07-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numero_patente', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('patente', 'Patente'), ('marca', 'Marca Registrada'), ('derecho_autor', 'Derecho de Autor'), ('secreto_comercial', 'Secreto Comercial')], max_length=100)),
                ('estado', models.CharField(choices=[('solicitud', 'En Solicitud'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vigente', 'Vigente'), ('expirada', 'Expirada')], max_length=100)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('inventores', models.JSONField(blank=True, default=list)),
                ('aplicacion_industrial', models.TextField(blank=True, null=True)),
                ('ventajas_tecnicas', models.JSONField(blank=True, default=list)),
                ('imagen_principal', models.URLField(blank=True, null=True)),
                ('documento_patente', models.URLField(blank=True, null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patente',
                'verbose_name_plural': 'Patentes',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoInnovacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('descripcion_corta', models.TextField(blank=True, null=True)),
                ('descripcion_larga', models.TextField(blank=True, null=True)),
                ('tipo_proyecto', models.CharField(choices=[('investigacion', 'Investigación'), ('desarrollo', 'Desarrollo'), ('implementacion', 'Implementación'), ('colaboracion', 'Colaboración')], max_length=100)),
                ('estado_proyecto', models.CharField(choices=[('planificacion', 'Planificación'), ('desarrollo', 'En Desarrollo'), ('pruebas', 'En Pruebas'), ('implementado', 'Implementado'), ('finalizado', 'Finalizado')], max_length=100)),
                ('tecnologias_utilizadas', models.JSONField(blank=True, default=list)),
                ('equipo_investigacion', models.JSONField(blank=True, default=list)),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('moneda', models.CharField(default='PEN', max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('resultados', models.JSONField(blank=True, default=list)),
                ('impacto_esperado', models.TextField(blank=True, null=True)),
                ('imagen_principal', models.URLField(blank=True, null=True)),
                ('galeria_imagenes', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto de Innovación',
                'verbose_name_plural': 'Proyectos de Innovación',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('descripcion_corta', models.TextField(blank=True, null=True)),
                ('descripcion_larga', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('mineria', 'Minería'), ('ambiental', 'Ambiental'), ('seguridad', 'Seguridad'), ('eficiencia', 'Eficiencia Energética'), ('digital', 'Transformación Digital')], max_length=100)),
                ('imagen_principal', models.URLField(blank=True, null=True)),
                ('galeria_imagenes', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('beneficios', models.JSONField(blank=True, default=list)),
                ('aplicaciones', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('destacado', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_implementacion', models.DateField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
