# Generated by Django 5.2.4 on 2025-07-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patente',
            name='documento_patente_url',
            field=models.URLField(blank=True, help_text='URL externa del documento de la patente (alternativa)', null=True),
        ),
        migrations.AddField(
            model_name='patente',
            name='imagen_principal_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen principal (alternativa)', null=True),
        ),
        migrations.AlterField(
            model_name='patente',
            name='documento_patente',
            field=models.FileField(blank=True, help_text='Documento de la patente subido al servidor (PDF recomendado)', null=True, upload_to='patentes/documentos/'),
        ),
        migrations.AlterField(
            model_name='patente',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='Imagen principal subida al servidor (recomendado: JPG, PNG)', null=True, upload_to='patentes/'),
        ),
    ]
