# Generated by Django 5.2.4 on 2025-07-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovacion', '0002_patente_documento_patente_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoinnovacion',
            name='imagen_principal_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen principal (alternativa)', null=True),
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='imagen_principal_url',
            field=models.URLField(blank=True, help_text='URL externa de la imagen principal (alternativa)', null=True),
        ),
        migrations.AlterField(
            model_name='proyectoinnovacion',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='Imagen principal subida al servidor (recomendado: JPG, PNG)', null=True, upload_to='proyectos/'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='Imagen principal subida al servidor (recomendado: JPG, PNG)', null=True, upload_to='tecnologias/'),
        ),
    ]
